# Generated by Django 3.2.6 on 2021-12-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('featured', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('S', 'shirt'), ('SW', 'Sports Wear'), ('OW', 'Outwear')], max_length=2)),
                ('label', models.CharField(choices=[('P', 'primary'), ('D', 'danger'), ('S', 'secondary')], max_length=1)),
                ('description', models.TextField()),
                ('quantity_available', models.IntegerField(default=1)),
            ],
        ),
    ]
