# Generated by Django 3.2.6 on 2021-12-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211221_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_on_homepage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CT', 'Cactus'), ('CL', 'Climbing'), ('FL', 'Flowering'), ('S', 'Succulent'), ('F', 'Fern')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1, null=True),
        ),
    ]
