# Generated by Django 3.2.6 on 2021-12-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211223_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('S', 'Succulent'), ('F', 'Fern'), ('FL', 'Flowering'), ('CL', 'Climbing'), ('CT', 'Cactus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('D', 'danger'), ('S', 'secondary')], max_length=1, null=True),
        ),
    ]
