# Generated by Django 3.2.6 on 2021-12-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20211227_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CL', 'Climbing'), ('FL', 'Flowering'), ('F', 'Fern'), ('CT', 'Cactus'), ('S', 'Succulent')], max_length=2),
        ),
    ]
